#!/bin/sh

set -e

APP_PATH=`pwd`

cd "$(dirname "$0")/.."

if ! test $(which forever)
then
  echo
  echo "!!!!"
  echo "You don't have forever installed. You need to install it first."
  echo
  echo "Just install it with this command: "
  echo 'sudo npm install forever -g'
  echo
  exit 1
fi

mkdir -p log

npm install

EOF

echo "Finished setting up itunes-api! run it with script/server or install it with script/install."
